version: '3.1'
services:
  db:
    image: postgres:10
    restart: always
    volumes:
      - ~/postgres_stuff/10:/var/lib/postgresql/data  # folder on your mac:folder in the docker instance
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432' 

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
    - db
    ports:
    - 5050:80 ## external exposed port: internal docker port
    ## you can change pgAdmin default username/password with below environment variables
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
