-- postgres formats 
-- standard sql
-- ISO 8601

-- different time interval formats


ALTER TABLE TEST_TIME ADD COLUMN SPAN INTERVAL;

SELECT * FROM TEST_TIME;

INSERT INTO TEST_TIME (SPAN, ACTION_TYPE) 
VALUES
('5 DECADES 3 YEARS 6 MONTHS 3 DAYS 12 HOURS', 'POSTGRES')




/* ------------------------------------------------------ */

ALTER TABLE TEST_TIME ADD COLUMN SPAN INTERVAL;

SELECT * FROM TEST_TIME;

INSERT INTO TEST_TIME (SPAN, ACTION_TYPE) 
VALUES
('5 DECADES 3 YEARS 6 MONTHS 3 DAYS 12 HOURS', 'POSTGRES')

INSERT INTO TEST_TIME (SPAN, ACTION_TYPE) 
VALUES
('1-2', 'SQL STD 2')

INSERT INTO TEST_TIME (SPAN, ACTION_TYPE) 
VALUES
('P5Y3M12D', 'ISO b')

INSERT INTO TEST_TIME (SPAN, ACTION_TYPE) 
VALUES
('P25-2-30T6:15', 'ISO c')

SHOW INTERVALSTYLE;

SET INTERVALSTYLE='postgres_verbose'